server:
  port: 54009
#    template:


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

#-1或者all  意味着producer得到follwer确认，才发送下一条数据

spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*
      use-only-site-local-interfaces: true
    consul:
      host: 192.186.3.44
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  datasource:
    url: jdbc:mysql://192.186.3.43:3306/bdp?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ymdx_p0o9i8u7y6
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      filter:
        stat:
          log-slow-sql: true
  kafka:
    bootstrap-servers: app-kafka-zk01.ycbus.com:9092,app-kafka-zk02.ycbus.com:9092,app-kafka-zk03.ycbus.com:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
  redis:
    timeout: 20000
    cluster:
      nodes: app-redis01.ycbus.com:7000,app-redis01.ycbus.com:7001,app-redis02.ycbus.com:7002,app-redis02.ycbus.com:7003,app-redis03.ycbus.com:7004
    password: 6PtE7AHIxJ541hv8IpXL
  #  redis:
#    timeout: 20000
#    host: 192.168.110.164
#    port: 6379
#    password: 93ormKe+4rc4aWLzohh8+jieshen
  application:
    name: ymdx-redis